spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/expense_manager?ApplicationName=expense-manager
    username: expense_manager
    password: q1w2e3r4
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.default_schema: app
    show_sql: true
logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.sql: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
server:
  port: 8080